---
title: "R Notebook"
output: html_notebook
---
```{r}
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(Hmisc)
library(dplyr)
library(caret)
library(superml)
library(ggcorrplot)

```


```{r}
df <- read.csv('C:\\Users\\Luis Perez\\Desktop\\heart_2020_cleaned.csv', header = TRUE,)



#testing for missing values
which(is.na(df))

df$HeartDisease <- as.factor(df$HeartDisease)
df$Smoking <- as.factor(df$Smoking)
df$AlcoholDrinking <- as.factor(df$AlcoholDrinking)
df$Stroke <- as.factor(df$Stroke)
df$PhysicalHealth <- as.factor(df$PhysicalHealth)
df$MentalHealth <- as.factor(df$MentalHealth)
df$DiffWalking <- as.factor(df$DiffWalking)
df$Sex <- as.factor(df$Sex)
df$AgeCategory <- as.factor(df$AgeCategory)
df$Race <- as.factor(df$Race)
df$Diabetic <- as.factor(df$Diabetic)
df$PhysicalActivity <- as.factor(df$PhysicalActivity)
df$GenHealth <- as.factor(df$GenHealth)
df$Asthma <- as.factor(df$Asthma)
df$KidneyDisease <- as.factor(df$KidneyDisease)
df$SkinCancer <- as.factor(df$SkinCancer)

#overview of data types
str(df)
table(df$HeartDisease)
```
```{r}
describe(df)
```

```{r}
par(mfrow = c(1, 2))
boxplot(df$BMI, main="BMI")
boxplot(df$SleepTime, main="Sleep Time")
boxplot(df$SleepTime, main="Sleep Time")

```
```{r}


p1 <- ggplot(data = df) +
  geom_bar(mapping = aes(x = Smoking))

p2 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =AlcoholDrinking ))

p3 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =Stroke ))
p4 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =DiffWalking ))

p5 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =Sex ))
p6 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =Race ))
p7 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =Diabetic ))

p8 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =PhysicalActivity ))

p9 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =GenHealth ))

p10 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =Asthma ))

p11 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =KidneyDisease ))

p12 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =SkinCancer ))

grid.arrange(p1, p2,p3, p4,p5, p6,p7, p8,p9, p10,p11, p12)




```
```{r}
# ask about this values

p13 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =PhysicalHealth ))

p14 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =MentalHealth ))

p15 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =AgeCategory ))


grid.arrange(p13,p14,p15)

```

```{r}
ph1<- ggplot(data = df) +
  geom_histogram(mapping = aes(x = BMI), binwidth = 0.5)

ph2<- ggplot(data = df) +
  geom_histogram(mapping = aes(x = SleepTime), binwidth = 0.5)

grid.arrange(ph1,ph2)

```


```{r}
p1 <- ggplot(data = df) +
  geom_bar(mapping = aes(x = Smoking))

p2 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =AlcoholDrinking ))

p3 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =Stroke ))
p4 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =DiffWalking ))

p5 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =Sex ))
p6 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =Race ))
p7 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =Diabetic ))

p8 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =PhysicalActivity ))

p9 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =GenHealth ))

p10 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =Asthma ))

p11 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =KidneyDisease ))

p12 <- ggplot(data = df) +
  geom_bar(mapping = aes(x =SkinCancer ))

grid.arrange(p1, p2,p3, p4,p5, p6,p7, p8,p9, p10,p11, p12)

#Smoking, AlcoholDrinking,Stroke,DiffWalking,Sex,Race,Diabetic,PhysicalActivity,GenHealth,Asthma,KidneyDisease,SkinCancer
```

```{r}
#subset sleep times based on normal sleeping hours
df1 <- subset(df,SleepTime >=4 & SleepTime <=12)

#Diabetic recode
df1$Diabetic<-recode(df1$Diabetic, Yes= "Yes",'Yes (during pregnancy)' ="Yes", 'No, borderline diabetes' = "No")

#dropping Race

#nominal data one hot encoding
df2 <- dummyVars(~ HeartDisease
                 +Smoking
                 +AlcoholDrinking
                 +Stroke
                 +DiffWalking
                 +Sex
                 +Diabetic
                 +PhysicalActivity
                 +Asthma
                 +KidneyDisease
                 +SkinCancer, data = df1, fullRank = T)

df3 <- data.frame(predict(df2, newdata= df1))

head(df3)

#label encoding for ordinal data  0 excellent...4 = very good ranked by abc order
#label <- LabelEncoder$new()
#df1$GenHealth <- label$fit_transform(df1$GenHealth)
df3$GenHealth <- df1$GenHealth
df3$BMI <- df1$BMI
df3$MentalHealth <- df1$MentalHealth
df3$PhysicalHealth <- df1$PhysicalHealth
```


```{r}
data(mtcars)
corr <- round(cor(df3), 1)
head(corr[, 1:6])
ggcorrplot(corr)
```

